test/common: move err() function to top of file
In preparation for adding new callers of err() to test/common, move
the err() function to the top of file. It has no dependencies, so
it can be first.

Signed-off-by: Marc Herbert <marc.herbert@linux.intel.com>
Reviewed-by: Dave Jiang <dave.jiang@intel.com>
Link: https://lore.kernel.org/r/20250724221323.365191-3-marc.herbert@linux.intel.com
[alison: edit commit message and log]
Signed-off-by: Alison Schofield <alison.schofield@intel.com>

diff --git a/test/common b/test/common
--- a/test/common
+++ b/test/common
@@ -1,6 +1,20 @@
 # SPDX-License-Identifier: GPL-2.0
 # Copyright (C) 2018, FUJITSU LIMITED. All rights reserved.
 
+# err
+# $1: line number which error detected
+# $2: cleanup function (optional)
+#
+
+test_basename=$(basename "$0")
+
+err()
+{
+	echo test/"$test_basename": failed at line "$1"
+	[ -n "$2" ] && "$2"
+	exit "$rc"
+}
+
 # Global variables
 
 # NDCTL
@@ -52,17 +66,6 @@ ACPI_BUS="ACPI.NFIT"
 E820_BUS="e820"
 
 # Functions
-
-# err
-# $1: line number which error detected
-# $2: cleanup function (optional)
-#
-err()
-{
-	echo test/$(basename $0): failed at line $1
-	[ -n "$2" ] && "$2"
-	exit $rc
-}
 
 reset()
 {
